# 7.2 Creating arrays from Existing Data
<b> The NumPy documentation recommends importing the numpy module as np so that you can access its members with "np.":</b>

In [1]:
import numpy as np

In [2]:
## The numpy mpdule provide various function for creating arrays.

In [3]:
numbers = np.array([2, 3, 5, 7, 11])

In [4]:
type(numbers)

numpy.ndarray

In [5]:
numbers

array([ 2,  3,  5,  7, 11])

<b>Multidimensional Arguments</b>

In [6]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

<b> Self Check</b>

In [1]:
import numpy as np

In [2]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [3]:
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

# 7.3 array Attributes
* An array object provides attributes that enable you to discover information about its structure and contents

In [1]:
import numpy as np

In [2]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
integers 

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [5]:
floats 

array([0. , 0.1, 0.2, 0.3, 0.4])

<b> Determining an array's Element Type </b>

In [6]:
integers.dtype

dtype('int32')

In [7]:
floats.dtype

dtype('float64')

<b>Determining an array's Dimensions</b>

In [8]:
integers.ndim

2

In [9]:
floats.ndim

1

In [10]:
integers.shape 

(2, 3)

In [11]:
floats.shape 

(5,)

<b> Determining an array's Number of Elements and Element Size</b>

In [12]:
integers.size

6

In [13]:
integers.itemsize

4

In [14]:
floats.size

5

In [15]:
floats.itemsize

8

<b> Iterating Through a Multidimensional array's Elements</b>

In [16]:
for row in integers:
    for column in row:
        print(column, end=' ')
    print()
    

1 2 3 
4 5 6 


In [17]:
# You can iterate through a multidimensional array as if it were one-dimensional by using its flat attribute:

for i in integers.flat:
    print(i, end=' ')
    

1 2 3 4 5 6 

<b>Self Check</b>

In [18]:
import numpy as np

In [19]:
a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [20]:
a.ndim

2

In [21]:
a.shape

(2, 5)

# 7.4 Filling arrays With Specific Values
<B> NumPy provides functions zeros, ones, and full for creating arrays containing 0s, 1s or a specified value.</B>

In [22]:
import numpy  as np

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.ones((2,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
np.full((3,5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

# 7.5 Creating arrays from Ranges

<b> Creating integer Ranges with arange</b>

In [26]:
import numpy as np

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [29]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

<b> Create Floating-Point Ranges with linspace </b>

In [30]:
np.linspace(0.0, 1.0, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

<b> Reshaping an array </b>

In [31]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

<b> Displaying Large arrays</b>

In [32]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [33]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

<b>Self Check</b>

In [34]:
import numpy as np

In [35]:
np.arange(2, 41, 2).reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

# 7.6 List vs. array Performance: introducing %timeit

<b> Timing the creation of a list containing results of 6,000,000 Die Rolls
</b>

In [1]:
import random

In [2]:
%timeit rolls_list = \
    [random.randrange(1, 7) for i in range(0, 6_000_000)]

3.12 s ± 41.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


<b> Timing the creation of an array containing results of 6,000,000 Die Rolls</b>

In [3]:
import numpy as np

In [4]:
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)

44.3 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


<b> 60,000,000 and 600,000,000 Die Rolls</b>

In [5]:
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)

453 ms ± 16.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)

4.47 s ± 105 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


<b> Customizing the %timeit Iterations</b>

In [7]:
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)

47.8 ms ± 1.83 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)


<b> Self Check </b>

In [8]:
import numpy as np

In [9]:
%timeit sum([x for x in range(1_000_000)])

54.6 ms ± 767 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit np.arange(10_000_000).sum()

12.8 ms ± 30.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# 7.7 array Operators

<b> Arithmetic Operations With arrays and Individual Numeric Values

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1,6)

In [3]:
numbers 

array([1, 2, 3, 4, 5])

In [4]:
numbers * 2

array([ 2,  4,  6,  8, 10])

In [5]:
numbers ** 3

array([  1,   8,  27,  64, 125], dtype=int32)

In [6]:
numbers  # numbers is unchanged by the arithmetic operators

array([1, 2, 3, 4, 5])

In [7]:
numbers += 10

In [8]:
numbers 

array([11, 12, 13, 14, 15])

<b>Broadcasting</b>

In [9]:
numbers * [2, 2, 2, 2, 2]

array([22, 24, 26, 28, 30])

<b> Arithmetic Operations Between arrays</b>

In [10]:
numbers2 = np.linspace(1.1, 5.5, 5)

In [11]:
numbers2 

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [12]:
numbers * numbers2

array([12.1, 26.4, 42.9, 61.6, 82.5])

<B> Comparing arrays</B>

In [13]:
numbers

array([11, 12, 13, 14, 15])

In [14]:
numbers>= 13

array([False, False,  True,  True,  True])

In [15]:
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [16]:
numbers2 < numbers

array([ True,  True,  True,  True,  True])

In [17]:
numbers == numbers2

array([False, False, False, False, False])

In [18]:
numbers == numbers

array([ True,  True,  True,  True,  True])

<b> Self Check </b>

In [19]:
import numpy as np

In [20]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])

# 7.8 Numpy Calculation Methods

In [21]:
import numpy as np

In [22]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [23]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [24]:
grades.sum()

1054

In [25]:
grades.min()

70

In [26]:
grades.max()

100

In [27]:
grades.mean()

87.83333333333333

In [28]:
grades.std()

8.792357792739987

In [29]:
grades.var()

77.30555555555556

<b> Calculations by Row or Column

In [30]:
grades.mean(axis=0)

array([95.25, 85.25, 83.  ])

In [31]:
grades.mean(axis=1)

array([84.33333333, 92.33333333, 87.        , 87.66666667])

<b> Self Check </b>

In [32]:
import numpy as np

In [33]:
grades = np.random.randint(60, 101, 12).reshape(3, 4)

In [34]:
grades 

array([[ 84,  85,  79,  72],
       [ 87,  97,  95,  76],
       [ 92, 100,  80,  72]])

In [35]:
grades.mean()

84.91666666666667

In [36]:
grades.mean(axis=0)

array([87.66666667, 94.        , 84.66666667, 73.33333333])

In [37]:
grades.mean(axis=1)

array([80.  , 88.75, 86.  ])

# 7.9 Universal Functions

In [38]:
import numpy as np

In [39]:
numbers = np.array([1, 4, 9, 16, 25, 36])

In [40]:
np.sqrt(numbers)

array([1., 2., 3., 4., 5., 6.])

In [41]:
numbers2 = np.arange(1, 7) * 10

In [42]:
numbers2

array([10, 20, 30, 40, 50, 60])

In [43]:
np.add(numbers, numbers2)

array([11, 24, 39, 56, 75, 96])

<b> Broadcasting With Universal Functions </b>

In [44]:
np.multiply(numbers2, 5)

array([ 50, 100, 150, 200, 250, 300])

In [45]:
numbers3 = numbers2.reshape(2, 3)

In [46]:
numbers3 

array([[10, 20, 30],
       [40, 50, 60]])

In [47]:
numbers4 = np.array([2, 4, 6])

In [48]:
np.multiply(numbers3, numbers4)

array([[ 20,  80, 180],
       [ 80, 200, 360]])

<b> Self Check</b>

In [49]:
import numpy as np

In [50]:
numbers = np.arange(1, 6)

In [51]:
np.power(numbers, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

# 7.10 Indexing and Slicing

<b>  Indexing with Two-Dimensional arrays </b>

In [52]:
import numpy as np

In [53]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [94, 77, 90], [100, 81, 82]])

In [54]:
grades 

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

In [55]:
grades[0, 1] # row 0, column 1

96

<b> selecting a subset of a Two-Dimensional array's Rows </b>

In [56]:
grades[1]

array([100,  87,  90])

In [57]:
grades[0:2]

array([[ 87,  96,  70],
       [100,  87,  90]])

In [58]:
grades[[1, 3]]

array([[100,  87,  90],
       [100,  81,  82]])

<b> selecting a Subset of a Two-Dimensional array's Columns </b>

In [59]:
grades[:, 0]

array([ 87, 100,  94, 100])

In [60]:
grades[:, 1:3]

array([[96, 70],
       [87, 90],
       [77, 90],
       [81, 82]])

In [61]:
grades[:, [0, 2]]

array([[ 87,  70],
       [100,  90],
       [ 94,  90],
       [100,  82]])

<b> Self Check </b>

In [62]:
import numpy as np 

In [63]:
a = np.arange(1, 16).reshape(3, 5)

In [64]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [65]:
a[1]

array([ 6,  7,  8,  9, 10])

In [66]:
a[[0, 2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [67]:
a[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

# 7.11 Views: Shallow Copies

In [1]:
import numpy as np

In [2]:
numbers = np.arange(1,6)
numbers

array([1, 2, 3, 4, 5])

In [3]:
numbers2 = numbers.view()

In [4]:
numbers2

array([1, 2, 3, 4, 5])

In [5]:
id(numbers)

2949207736752

In [6]:
id(numbers2)

2949207997008

In [7]:
numbers[1] *= 10

In [8]:
numbers2

array([ 1, 20,  3,  4,  5])

In [9]:
numbers

array([ 1, 20,  3,  4,  5])

In [10]:
numbers2[1] /= 10

In [11]:
numbers2

array([1, 2, 3, 4, 5])

In [12]:
numbers

array([1, 2, 3, 4, 5])

In [13]:
numbers2 = numbers[0:3]

In [14]:
numbers2 

array([1, 2, 3])

In [15]:
id(numbers)

2949207736752

In [16]:
id(numbers2)

2949208527088

In [17]:
numbers[1] *= 20

In [18]:
numbers

array([ 1, 40,  3,  4,  5])

In [19]:
numbers2

array([ 1, 40,  3])

# 7.12 Deep Copies

In [20]:
import numpy as np

In [21]:
numbers = np.arange(1, 6)

In [22]:
numbers 

array([1, 2, 3, 4, 5])

In [23]:
numbers2 = numbers.copy()

In [24]:
numbers2 

array([1, 2, 3, 4, 5])

In [25]:
numbers[1] *= 10

In [26]:
numbers

array([ 1, 20,  3,  4,  5])

In [27]:
numbers2

array([1, 2, 3, 4, 5])

# 7.13 Reshaping and Transposing

<b> reshape vs resize </b>

In [28]:
import numpy as np

In [29]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [30]:
grades 

array([[ 87,  96,  70],
       [100,  87,  90]])

In [31]:
grades.reshape(1,6)

array([[ 87,  96,  70, 100,  87,  90]])

In [32]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [33]:
grades.resize(1, 6)

In [34]:
grades

array([[ 87,  96,  70, 100,  87,  90]])

<b> flatten vs. ravel</b>

In [35]:
grades = np.array([[87, 96, 70], [100, 87, 90]])

In [36]:
grades 

array([[ 87,  96,  70],
       [100,  87,  90]])

In [37]:
flattened = grades.flatten()

In [38]:
flattened 

array([ 87,  96,  70, 100,  87,  90])

In [39]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [40]:
flattened[0] = 100

In [41]:
flattened

array([100,  96,  70, 100,  87,  90])

In [42]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [43]:
raveled = grades.ravel()

In [44]:
raveled

array([ 87,  96,  70, 100,  87,  90])

In [45]:
grades

array([[ 87,  96,  70],
       [100,  87,  90]])

In [46]:
raveled[0] = 100

In [47]:
raveled

array([100,  96,  70, 100,  87,  90])

In [48]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

<b> Transposing Rows and Columns</b>

In [49]:
grades.T

array([[100, 100],
       [ 96,  87],
       [ 70,  90]])

In [50]:
grades

array([[100,  96,  70],
       [100,  87,  90]])

<b> Horizontal and Vertical Stacking</b>

In [51]:
grades2 = np.array([[94, 77, 90], [100, 81, 82]])

In [52]:
grades2

array([[ 94,  77,  90],
       [100,  81,  82]])

In [53]:
np.hstack((grades, grades2))

array([[100,  96,  70,  94,  77,  90],
       [100,  87,  90, 100,  81,  82]])

In [54]:
np.vstack((grades, grades2))

array([[100,  96,  70],
       [100,  87,  90],
       [ 94,  77,  90],
       [100,  81,  82]])

<b> Self Check</b>

In [55]:
import numpy as np

In [56]:
a = np.arange(1, 7).reshape(2, 3)

In [57]:
a = np.hstack((a, a))

In [58]:
a = np.vstack((a, a))

In [59]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
print('My name is Naiema Elsaadi')

My name is Naiema Elsaadi
